// <auto-generated />
using System;
using GradeAndAssessment.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GradeAndAssessment.Api.Migrations
{
    [DbContext(typeof(StudentAssessmentContext))]
    [Migration("20230530201039_FourthMigration")]
    partial class FourthMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GradeAndAssessment.Api.Data.StudentAssessment", b =>
                {
                    b.Property<string>("AssessmentId")
                        .HasColumnType("text");

                    b.Property<decimal>("Assignment")
                        .HasColumnType("numeric");

                    b.Property<string>("CourseId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EndOfSemExam")
                        .HasColumnType("numeric");

                    b.Property<string>("IndexNumber")
                        .HasColumnType("text");

                    b.Property<decimal>("MidsemExam")
                        .HasColumnType("numeric");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("bytea");

                    b.Property<decimal>("Project")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Score")
                        .HasColumnType("numeric");

                    b.Property<string>("TeacherName")
                        .HasColumnType("text");

                    b.HasKey("AssessmentId");

                    b.ToTable("StudentAssessments");
                });
#pragma warning restore 612, 618
        }
    }
}
